[[plugins]] # coc
repo = 'neoclide/coc.nvim'
if = 'g:registered_lsp ==# "coc"'
merged = 0
rev = 'release'
hook_add = '''
    source $VIM_PATH/config/coc.vim
'''

[[plugins]] # snippets
repo = 'honza/vim-snippets'
if = 'has("python3")'
merged = 0

# [[plugins]]
# repo = 'LunarWatcher/auto-pairs'
#
[[plugins]]# 自动配对
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_source = '''
let g:lexima_no_default_rules = 1
call lexima#set_default_rules()
if g:registered_lsp ==# 'coc'
    inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
endif
'''
# [[plugins]]
# repo = 'gelguy/wilder.nvim'
# hook_source = '''
#     call wilder#setup({'modes': [':', '/', '?']})
# '''
